export const SERVICE_CATEGORIES = [
  "4 Point",
  "Asbestos",
  "Commercial",
  "Consultation",
  "Draw Inspection",
  "Hvac",
  "Lead",
  "Limited Scope",
  "Manufactured Home",
  "Misc",
  "Mobile Home",
  "Mold",
  "Multi Unit",
  "New Construction",
  "Pest",
  "Pool",
  "Pre Drywall",
  "Pre Listing",
  "Radon",
  "Re Inspections",
  "Rental",
  "Residential",
  "Roof",
  "Sewer Septic",
  "Structural",
  "Termite",
  "Thermal",
  "Walkthrough",
  "Warranty",
  "Water",
  "Wind Mitigation",
];


